workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"   # Ref: https://docs.gitlab.com/ee/ci/yaml/workflow.html
      when: never
    - when: always

stages:
  - test
  - build

run_unit_test:
  image: node:17-alpine3.14
  stage: test
  tags:
    - runner-2
  before_script:
    - cd app
    - npm install
  script:
    - npm test
  artifacts:
    when: always    # Report will visible for fail and pass case
    paths:
      - app/junit.xml   # Test's result path
    reports:
      junit: app/junit.xml    # Report path


build_image:
  variables:
    NODE_IMAGE: test-gitlab-runner.com/test/node-js-app
    DEV_ENV: dev
  stage: build
  tags:
    - test-runner-1
  script:
    - docker build . -f Dockerfile -t $NODE_IMAGE/$DEV_ENV:v1.0.9


push_image:
  variables:
    GITLAB_REPO: test-gitlab-runner.com
    NODE_IMAGE: test-gitlab-runner.com/test/node-js-app
    DEV_ENV: dev
  stage: build
  needs:
    - build_image
  tags:
    - test-runner-1
  before_script:
    - docker login $GITLAB_REPO
  script:
    - docker push $NODE_IMAGE/$DEV_ENV:v1.0.9