workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never


variables:
  CI_REGISTRY_NAME: test-gitlab-runner.com
  IMAGE_NAME: node_app
  IMAGE_VERSION: v1
  DC_IMAGE_NAME: $CI_REGISTRY_NAME/$CI_PROJECT_NAME/$IMAGE_NAME


stages:
  - build
  - push
  - deploy


build_image:
  tags:
    - test-runner-1
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_NAME
    - export PACKAGE_JSON_VERSION=$(cat app/package.json | jq -r '.version')
    - export APP_VERSION=$PACKAGE_JSON_VERSION.$CI_PIPELINE_IID
    - echo $APP_VERSION > version-file.txt
  script:
    - docker build -t $CI_REGISTRY_NAME/$CI_PROJECT_NAME/$IMAGE_NAME:$APP_VERSION .
  artifacts:
    paths:
      - version-file.txt


push_image:
  tags:
    - test-runner-1
  stage: push
  needs:
    - build_image
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_NAME
    - export APP_VERSION=$(cat version-file.txt)
  script:
    - docker push $CI_REGISTRY_NAME/$CI_PROJECT_NAME/$IMAGE_NAME:$APP_VERSION


deployment:
  variables:
    RUNNER_NAME: gitlab-runner
    RUNNER_IP: 172.16.7.239
    CONTAINER_NAME: node_app
    INTERNAL_PORT: 3000
    EXPOSE_PORT: 3000
  tags:
    - test-runner-1
  stage: deploy
  needs:
    - build_image
    - push_image
  before_script:
    - export APP_VERSION=$(cat version-file.txt)
    - scp -o StrictHostKeyChecking=no ./docker-compose.yaml $RUNNER_NAME@$RUNNER_IP:/tmp/docker-compose.yaml
  script:
    - ssh -o StrictHostKeyChecking=no $RUNNER_NAME@$RUNNER_IP "

      export DC_IMAGE_NAME=$DC_IMAGE_NAME &&
      export IMAGE_VERSION=$APP_VERSION &&

      docker pull $CI_REGISTRY_NAME/$CI_PROJECT_NAME/$IMAGE_NAME:$IMAGE_VERSION &&
      docker-compose -f /tmp/docker-compose.yaml down &&
      docker-compose -f /tmp/docker-compose.yaml up -d"
  environment:
    name: development
    url: http://172.16.7.239:3000/